### ISSUE TITLE
有点错误，难道是因为ID里的字符？

### ISSUE THREAD

**Issue by Gawainc** [yangxuanxc/wechat_friends#1]
Login successfully as XXXคิดถึง
Traceback (most recent call last):
  File "get_user_info.py", line 65, in <module>
    save_data(friends_list)
  File "get_user_info.py", line 33, in save_data
    json_file.write(json.dumps(frined_list,ensure_ascii=False))
UnicodeEncodeError: 'gbk' codec can't encode character '\u0e04' in position 20: illegal multibyte sequence

**Comment by Timerun16ning** [comment]
python版本问题吧，你用低版本的试试

**Comment by yangxuanxc** [comment]
我这里用的是python3.6 你那里按照提示应该是编码错误了，我估计是版本问题。

**Comment by sym44** [comment]
使用3.6.3，有同样的问题。
应该是utf-8字符识别问题，可以用
`import codecs`

`with codecs.open(out_file_name, 'w', encoding='utf-8') as json_file:`
`    json_file.write(json.dumps(frined_list,ensure_ascii=False))`

来修复该问题。已提交pull request @yangxuanxc @Gawainc

**Comment by yangxuanxc** [comment]
已合入，thanks
