### ISSUE TITLE
analyse.py运行错误

### ISSUE THREAD

**Issue by SlowFlight** [yangxuanxc/wechat_friends#22]
求问这是什么情况
E:\tools\python\wechat_friends-master>python analyse.py
Traceback (most recent call last):
  File "analyse.py", line 6, in <module>
    from pyecharts import Bar
  File "E:\tools\python3\lib\site-packages\pyecharts\__init__.py", line 10, in <
module>
    from pyecharts.charts.effectscatter import EffectScatter
  File "E:\tools\python3\lib\site-packages\pyecharts\charts\effectscatter.py", l
ine 3, in <module>
    from pyecharts.charts.scatter import Scatter
  File "E:\tools\python3\lib\site-packages\pyecharts\charts\scatter.py", line 3,
 in <module>
    from PIL import Image
  File "E:\tools\python3\lib\site-packages\PIL\Image.py", line 64, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging'

**Comment by SlowFlight** [comment]
python3.7的锅
