### ISSUE TITLE
analyse.py line175 and 898 FileNotFoundError: [Errno 2] No such file or directory: './data/friends.json'

### ISSUE THREAD

**Issue by xxyyffyeah** [yangxuanxc/wechat_friends#30]
I haven't found the file path related to friends.json.
And how can i create it?

**Comment by blockchainsecure** [comment]
Login successfully as 绁炶伔浜哄摗鈧縤tcoin
Traceback (most recent call last):
  File "get_user_info.py", line 66, in <module>
    save_data(friends_list)
  File "get_user_info.py", line 34, in save_data
    json_file.write(json.dumps(frined_list,ensure_ascii=False))
  File "C:\Python27\lib\json\__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 210, in encode
    return ''.join(chunks)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 1: ordinal
