### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'page_title'

### ISSUE THREAD

**Issue by AndyyWei** [yangxuanxc/wechat_friends#33]
Traceback (most recent call last):
  File "/Users/andy/PycharmProjects/wechat_friends-master/analyse.py", line 199, in <module>
    get_pie('性别统计', name_list, num_list)
  File "/Users/andy/PycharmProjects/wechat_friends-master/analyse.py", line 24, in get_pie
    subtitle=subtitle, subtitle_text_size=25, width=800, height=800)
TypeError: __init__() got an unexpected keyword argument 'page_title'

**Comment by taohy88** [comment]
I already have the problem,How to resolve it

**Comment by kkkkwq** [comment]
I have the error,too
